use warehouse
--InsumosIventario
--Mayo
INSERT INTO [dbo].[insumosInventario] ([nombre_insumo], [cantidad], [fecha])
VALUES
    ('Cuerda de Colores', 500, '2023-05-01'),
    ('Beads de Plástico', 1000, '2023-05-02'),
    ('Cierre Metálico', 200, '2023-05-03'),
    ('Hilo Elástico', 800, '2023-05-04'),
    ('Charm Dorado', 150, '2023-05-05'),
    ('Abalorios de Cristal', 300, '2023-05-06'),
    ('Cadena Plateada', 250, '2023-05-07'),
    ('Colgante de Corazón', 50, '2023-05-08'),
    ('Beads de Madera', 600, '2023-05-09'),
    ('Hilo de Seda', 350, '2023-05-10'),
    ('Charm Plateado', 120, '2023-05-11'),
    ('Cierre de Plástico', 400, '2023-05-12'),
    ('Cordón de Cuero', 180, '2023-05-13'),
    ('Beads de Metal', 280, '2023-05-14'),
    ('Abalorios de Cerámica', 220, '2023-05-15'),
    ('Cadena Dorada', 190, '2023-05-16'),
    ('Colgante de Estrella', 80, '2023-05-17'),
    ('Cierre Magnético', 300, '2023-05-18'),
    ('Hilo de Nylon', 420, '2023-05-19'),
    ('Charm de Mariposa', 110, '2023-05-20');
GO

--Junio
INSERT INTO [dbo].[insumosInventario] ([nombre_insumo], [cantidad], [fecha])
VALUES
    ('Cuerda de Colores', 600, '2023-06-01'),
    ('Beads de Plástico', 1200, '2023-06-02'),
    ('Cierre Metálico', 250, '2023-06-03'),
    ('Hilo Elástico', 900, '2023-06-04'),
    ('Charm Dorado', 200, '2023-06-05'),
    ('Abalorios de Cristal', 350, '2023-06-06'),
    ('Cadena Plateada', 300, '2023-06-07'),
    ('Colgante de Corazón', 70, '2023-06-08'),
    ('Beads de Madera', 750, '2023-06-09'),
    ('Hilo de Seda', 400, '2023-06-10'),
    ('Charm Plateado', 140, '2023-06-11'),
    ('Cierre de Plástico', 450, '2023-06-12'),
    ('Cordón de Cuero', 220, '2023-06-13'),
    ('Beads de Metal', 320, '2023-06-14'),
    ('Abalorios de Cerámica', 260, '2023-06-15'),
    ('Cadena Dorada', 220, '2023-06-16'),
    ('Colgante de Estrella', 90, '2023-06-17'),
    ('Cierre Magnético', 350, '2023-06-18'),
    ('Hilo de Nylon', 480, '2023-06-19'),
    ('Charm de Mariposa', 130, '2023-06-20');
GO
--Productos Inventario
--Mayo
INSERT INTO [dbo].[productosInventario] ([nombre_producto], [cantidad], [fecha])
VALUES
    ('Pulsera de Cuentas', 50, '2023-05-01'),
    ('Pulsera de Charms', 30, '2023-05-02'),
    ('Pulsera de Cuero', 20, '2023-05-03'),
    ('Pulsera Tejida', 40, '2023-05-04'),
    ('Pulsera de Cadena', 25, '2023-05-05'),
    ('Pulsera con Colgante', 35, '2023-05-06'),
    ('Pulsera Elegante', 15, '2023-05-07'),
    ('Pulsera de Perlas', 10, '2023-05-08'),
    ('Pulsera de Cuerda', 60, '2023-05-09'),
    ('Pulsera de Metal', 45, '2023-05-10'),
    ('Pulsera de Cristal', 55, '2023-05-11'),
    ('Pulsera Bohemia', 28, '2023-05-12'),
    ('Pulsera Minimalista', 18, '2023-05-13'),
    ('Pulsera de Plata', 33, '2023-05-14'),
    ('Pulsera Vintage', 22, '2023-05-15'),
    ('Pulsera de Mariposa', 12, '2023-05-16'),
    ('Pulsera de Estrella', 38, '2023-05-17'),
    ('Pulsera de Amistad', 42, '2023-05-18'),
    ('Pulsera de Piedras Preciosas', 27, '2023-05-19'),
    ('Pulsera de Abalorios', 47, '2023-05-20'),
    ('Pulsera con Dijes', 23, '2023-05-21'),
    ('Pulsera de Tela', 32, '2023-05-22'),
    ('Pulsera de Madera', 37, '2023-05-23'),
    ('Pulsera de Nudo', 19, '2023-05-24'),
    ('Pulsera de Playa', 14, '2023-05-25'),
    ('Pulsera de Moda', 31, '2023-05-26'),
    ('Pulsera de Fiesta', 26, '2023-05-27'),
    ('Pulsera Boho', 29, '2023-05-28'),
    ('Pulsera de Acero Inoxidable', 21, '2023-05-29'),
    ('Pulsera Étnica', 16, '2023-05-30');
GO

--junio
INSERT INTO [dbo].[productosInventario] ([nombre_producto], [cantidad], [fecha])
VALUES
    ('Pulsera de Cuentas', 55, '2023-06-01'),
    ('Pulsera de Charms', 28, '2023-06-02'),
    ('Pulsera de Cuero', 18, '2023-06-03'),
    ('Pulsera Tejida', 38, '2023-06-04'),
    ('Pulsera de Cadena', 23, '2023-06-05'),
    ('Pulsera con Colgante', 33, '2023-06-06'),
    ('Pulsera Elegante', 13, '2023-06-07'),
    ('Pulsera de Perlas', 8, '2023-06-08'),
    ('Pulsera de Cuerda', 65, '2023-06-09'),
    ('Pulsera de Metal', 42, '2023-06-10'),
    ('Pulsera de Cristal', 50, '2023-06-11'),
    ('Pulsera Bohemia', 25, '2023-06-12'),
    ('Pulsera Minimalista', 15, '2023-06-13'),
    ('Pulsera de Plata', 29, '2023-06-14'),
    ('Pulsera Vintage', 20, '2023-06-15'),
    ('Pulsera de Mariposa', 10, '2023-06-16'),
    ('Pulsera de Estrella', 35, '2023-06-17'),
    ('Pulsera de Amistad', 40, '2023-06-18'),
    ('Pulsera de Piedras Preciosas', 22, '2023-06-19'),
    ('Pulsera de Abalorios', 45, '2023-06-20'),
    ('Pulsera con Dijes', 21, '2023-06-21'),
    ('Pulsera de Tela', 30, '2023-06-22'),
    ('Pulsera de Madera', 35, '2023-06-23'),
    ('Pulsera de Nudo', 16, '2023-06-24'),
    ('Pulsera de Playa', 11, '2023-06-25'),
    ('Pulsera de Moda', 28, '2023-06-26'),
    ('Pulsera de Fiesta', 23, '2023-06-27'),
    ('Pulsera Boho', 26, '2023-06-28'),
    ('Pulsera de Acero Inoxidable', 19, '2023-06-29'),
    ('Pulsera Étnica', 14, '2023-06-30');

GO


--ComprasClientes
--mayo
INSERT INTO [dbo].[rankingClientes] ([nombre_cliente], [numero_compras], [fecha])
VALUES
    ('Juan Hernández', 2, '2023-05-01'),
    ('María Rodríguez', 4, '2023-05-02'),
    ('Miguel González', 3, '2023-05-03'),
    ('Ana Martínez', 3, '2023-05-04'),
    ('José López', 5, '2023-05-05');

GO



--junio 
INSERT INTO [dbo].[rankingClientes] ([nombre_cliente], [numero_compras], [fecha])
VALUES
    ('Juan Hernández', 5, '2023-06-01'),
    ('María Rodríguez', 9, '2023-06-02'),
    ('Miguel González', 7, '2023-06-03'),
    ('Ana Martínez', 12, '2023-06-04'),
    ('José López', 10, '2023-06-05');

GO
 

--Ventas
--Mayo
INSERT INTO [dbo].[venta] ([nombreproducto], [numero_ventas], [recuadado_por_venta], [fecha])
VALUES
    ('Pulsera de Cuentas', 20, 500.00, '2023-05-01'),
    ('Pulsera de Charms', 15, 350.00, '2023-05-02'),
    ('Pulsera de Cuero', 10, 300.00, '2023-05-03'),
    ('Pulsera Tejida', 18, 400.00, '2023-05-04'),
    ('Pulsera de Cadena', 12, 250.00, '2023-05-05'),
    ('Pulsera con Colgante', 14, 320.00, '2023-05-06'),
    ('Pulsera Elegante', 8, 220.00, '2023-05-07'),
    ('Pulsera de Perlas', 6, 180.00, '2023-05-08'),
    ('Pulsera de Cuerda', 22, 550.00, '2023-05-09'),
    ('Pulsera de Metal', 16, 380.00, '2023-05-10');

GO

--junio
INSERT INTO [dbo].[venta] ([nombreproducto], [numero_ventas], [recuadado_por_venta], [fecha])
VALUES
    ('Pulsera de Cuentas', 25, 600.00, '2023-06-01'),
    ('Pulsera de Charms', 20, 450.00, '2023-06-02'),
    ('Pulsera de Cuero', 15, 400.00, '2023-06-03'),
    ('Pulsera Tejida', 22, 550.00, '2023-06-04'),
    ('Pulsera de Cadena', 18, 380.00, '2023-06-05'),
    ('Pulsera con Colgante', 21, 480.00, '2023-06-06'),
    ('Pulsera Elegante', 12, 320.00, '2023-06-07'),
    ('Pulsera de Perlas', 8, 240.00, '2023-06-08'),
    ('Pulsera de Cuerda', 28, 700.00, '2023-06-09'),
    ('Pulsera de Metal', 19, 420.00, '2023-06-10');

GO


